if(APPLE)
    set(CMAKE_PREFIX_PATH "/opt/Qt/6.10.0/macos")
elseif(WIN32)
    set(CMAKE_PREFIX_PATH "C:/Qt/6.10.0/msvc2022_64")
elseif(UNIX AND NOT APPLE)
    set(CMAKE_PREFIX_PATH "/opt/Qt/6.10.0/gcc_64")
else()
    message(FATAL_ERROR "Unsupported platform for Qt6")
endif()
